# -*- coding: utf-8 -*-
"""eksekusi code dari Datacamp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13eMwovrW5QMxb0YgbcVrQdCTQRYWedFs

[Datacamp](https://www.datacamp.com/datalab/w/9ebb6885-381c-49df-92fc-52d56572c0ea/edit).
"""